ASSIGNMENT: CREATE A RANDOM SAMPLE OF 120 FARMERS FROM THE 3 COUNTIES.

Each county should have a sample of 40 farmers based on the criteria below.
-Sex of farmer (male/female)
-Age – breakdown by 17-29 (sample of both male and female), and 30-65 (both male and female)
-Clustering per village (villages with low, medium and high concentration of farmers)
-Cohorts (referred to in Excel sheet as “instance”) – sampling across cohorts (when farmers were recruited)

In [85]:
#Import necessary libraries
import pandas as pd

In [86]:
data=pd.read_csv("C:\\Users\\Administrator\\OneDrive\\Documents\\List of Farmer for Sample Size Selection- Quality Evaluation_Confidential.csv")
data.head()

,No,FG ID,Forest Garden Name,Project Unit Name,Village,Local Group Name,Instance,Gender,Age
0,1,FG-024543,Oloo michael,Kenya: Homa Bay 7,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Male,17
1,2,FG-024544,Susan Adhiambo Ochieng,Kenya: Homa Bay 7,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Female,29
2,3,FG-048934,Agapitus Ouma Abuga,Kenya: Homa Bay 11,SIGAMA GAYENA,Bet Kimiyi Farmers Group,Instance 3,Male,45
3,4,FG-024165,REUBEN OLOO AYIEMBA,Kenya: Homa Bay 7,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Male,43
4,5,FG-073891,ASSENATH ACHIENG OTIENO,Kenya: Homa Bay 11,SIGAMA GAYENA,Bet Kimiyi Farmers Group,Instance 3,Female,50

In [87]:
#Part 1: Clustering per village
village_counts=data["Village"].value_counts()
#define concentration
high_conc=village_counts.quantile(0.66)
low_conc=village_counts.quantile(0.33)

def village_clusters(x):
    if village_counts[x]>=high_conc:
        return "high"
    elif village_counts[x]>=low_conc:
        return "low"
    else:
        return "medium"

data["village_clusters"]=data["Village"].map(village_clusters)

In [88]:
#Part 2: Creating age groups broken down by gender
bins=[17,29,65]
labels=["17-29", "30-65"]
data["age_group"]=pd.cut(data["Age"], bins=bins, labels=labels, right=True, include_lowest=True)
data=data.dropna()
data

,No,FG ID,Forest Garden Name,Project Unit Name,Village,Local Group Name,Instance,Gender,Age,village_clusters,age_group
0,1,FG-024543,Oloo michael,Kenya: Homa Bay 7,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Male,17,medium,17-29
1,2,FG-024544,Susan Adhiambo Ochieng,Kenya: Homa Bay 7,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Female,29,medium,17-29
2,3,FG-048934,Agapitus Ouma Abuga,Kenya: Homa Bay 11,SIGAMA GAYENA,Bet Kimiyi Farmers Group,Instance 3,Male,45,low,30-65
3,4,FG-024165,REUBEN OLOO AYIEMBA,Kenya: Homa Bay 7,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Male,43,medium,30-65
4,5,FG-073891,ASSENATH ACHIENG OTIENO,Kenya: Homa Bay 11,SIGAMA GAYENA,Bet Kimiyi Farmers Group,Instance 3,Female,50,low,30-65
...,...,...,...,...,...,...,...,...,...,...,...
15755,15756,FG-071316,Millicent Demba Ochieng,Kenya: Migori 9,Nyaera,Waweya Moyie Farmers Group,Instance 4,Female,47,high,30-65
15756,15757,FG-068488,Molly Anyango Otieno,Kenya: Migori 9,Nyaera,Waweya Moyie Farmers Group,Instance 4,Female,38,high,30-65
15757,15758,FG-092514,Peter Ojea Magadi,Kenya: Migori 9,Nyaera,Waweya Moyie Farmers Group,Instance 4,Male,30,high,30-65
15759,15760,FG-068489,Tobias Otieno Olela,Kenya: Migori 9,Nyaera,Waweya Moyie Farmers Group,Instance 4,Male,38,high,30-65
15760,15761,FG-092513,Zablon Mahonga Muyesu,Kenya: Migori 9,Nyaera,Waweya Moyie Farmers Group,Instance 4,Male,42,high,30-65

In [89]:
#check for null values
data.isna().sum()

No                    0
FG ID                 0
Forest Garden Name    0
Project Unit Name     0
Village               0
Local Group Name      0
Instance              0
Gender                0
Age                   0
village_clusters      0
age_group             0
dtype: int64

In [90]:
#change the data type
data["age_gender_group"]=data["Gender"].astype(str) + "_" + data["age_group"].astype(str)

In [91]:
#Splitting the County column
data[["country", "rest"]]=data["Project Unit Name"].str.split(":", n=1, expand=True)
data

,No,FG ID,Forest Garden Name,Project Unit Name,Village,Local Group Name,Instance,Gender,Age,village_clusters,age_group,age_gender_group,country,rest
0,1,FG-024543,Oloo michael,Kenya: Homa Bay 7,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Male,17,medium,17-29,Male_17-29,Kenya,Homa Bay 7
1,2,FG-024544,Susan Adhiambo Ochieng,Kenya: Homa Bay 7,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Female,29,medium,17-29,Female_17-29,Kenya,Homa Bay 7
2,3,FG-048934,Agapitus Ouma Abuga,Kenya: Homa Bay 11,SIGAMA GAYENA,Bet Kimiyi Farmers Group,Instance 3,Male,45,low,30-65,Male_30-65,Kenya,Homa Bay 11
3,4,FG-024165,REUBEN OLOO AYIEMBA,Kenya: Homa Bay 7,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Male,43,medium,30-65,Male_30-65,Kenya,Homa Bay 7
4,5,FG-073891,ASSENATH ACHIENG OTIENO,Kenya: Homa Bay 11,SIGAMA GAYENA,Bet Kimiyi Farmers Group,Instance 3,Female,50,low,30-65,Female_30-65,Kenya,Homa Bay 11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15755,15756,FG-071316,Millicent Demba Ochieng,Kenya: Migori 9,Nyaera,Waweya Moyie Farmers Group,Instance 4,Female,47,high,30-65,Female_30-65,Kenya,Migori 9
15756,15757,FG-068488,Molly Anyango Otieno,Kenya: Migori 9,Nyaera,Waweya Moyie Farmers Group,Instance 4,Female,38,high,30-65,Female_30-65,Kenya,Migori 9
15757,15758,FG-092514,Peter Ojea Magadi,Kenya: Migori 9,Nyaera,Waweya Moyie Farmers Group,Instance 4,Male,30,high,30-65,Male_30-65,Kenya,Migori 9
15759,15760,FG-068489,Tobias Otieno Olela,Kenya: Migori 9,Nyaera,Waweya Moyie Farmers Group,Instance 4,Male,38,high,30-65,Male_30-65,Kenya,Migori 9
15760,15761,FG-092513,Zablon Mahonga Muyesu,Kenya: Migori 9,Nyaera,Waweya Moyie Farmers Group,Instance 4,Male,42,high,30-65,Male_30-65,Kenya,Migori 9

In [92]:
data["country"] = data["country"].str.strip()
data["rest"] = data["rest"].str.strip()

In [93]:
data[["County", "zone_no"]]=data["rest"].str.rsplit(" ", n=1, expand=True)
data.head()

,No,FG ID,Forest Garden Name,Project Unit Name,Village,Local Group Name,Instance,Gender,Age,village_clusters,age_group,age_gender_group,country,rest,County,zone_no
0,1,FG-024543,Oloo michael,Kenya: Homa Bay 7,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Male,17,medium,17-29,Male_17-29,Kenya,Homa Bay 7,Homa Bay,7
1,2,FG-024544,Susan Adhiambo Ochieng,Kenya: Homa Bay 7,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Female,29,medium,17-29,Female_17-29,Kenya,Homa Bay 7,Homa Bay,7
2,3,FG-048934,Agapitus Ouma Abuga,Kenya: Homa Bay 11,SIGAMA GAYENA,Bet Kimiyi Farmers Group,Instance 3,Male,45,low,30-65,Male_30-65,Kenya,Homa Bay 11,Homa Bay,11
3,4,FG-024165,REUBEN OLOO AYIEMBA,Kenya: Homa Bay 7,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Male,43,medium,30-65,Male_30-65,Kenya,Homa Bay 7,Homa Bay,7
4,5,FG-073891,ASSENATH ACHIENG OTIENO,Kenya: Homa Bay 11,SIGAMA GAYENA,Bet Kimiyi Farmers Group,Instance 3,Female,50,low,30-65,Female_30-65,Kenya,Homa Bay 11,Homa Bay,11

In [94]:
#Drop unnecessary columns
data=data.drop(columns=["Project Unit Name", "country", "rest", "zone_no"])
data.head()

,No,FG ID,Forest Garden Name,Village,Local Group Name,Instance,Gender,Age,village_clusters,age_group,age_gender_group,County
0,1,FG-024543,Oloo michael,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Male,17,medium,17-29,Male_17-29,Homa Bay
1,2,FG-024544,Susan Adhiambo Ochieng,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Female,29,medium,17-29,Female_17-29,Homa Bay
2,3,FG-048934,Agapitus Ouma Abuga,SIGAMA GAYENA,Bet Kimiyi Farmers Group,Instance 3,Male,45,low,30-65,Male_30-65,Homa Bay
3,4,FG-024165,REUBEN OLOO AYIEMBA,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Male,43,medium,30-65,Male_30-65,Homa Bay
4,5,FG-073891,ASSENATH ACHIENG OTIENO,SIGAMA GAYENA,Bet Kimiyi Farmers Group,Instance 3,Female,50,low,30-65,Female_30-65,Homa Bay

In [95]:
data["County"] = data["County"].replace({"Homa Bay":"HomaBay"})
data

,No,FG ID,Forest Garden Name,Village,Local Group Name,Instance,Gender,Age,village_clusters,age_group,age_gender_group,County
0,1,FG-024543,Oloo michael,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Male,17,medium,17-29,Male_17-29,HomaBay
1,2,FG-024544,Susan Adhiambo Ochieng,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Female,29,medium,17-29,Female_17-29,HomaBay
2,3,FG-048934,Agapitus Ouma Abuga,SIGAMA GAYENA,Bet Kimiyi Farmers Group,Instance 3,Male,45,low,30-65,Male_30-65,HomaBay
3,4,FG-024165,REUBEN OLOO AYIEMBA,LANGI VILLAGE,LANGI FARMERS GROUP,Instance 2,Male,43,medium,30-65,Male_30-65,HomaBay
4,5,FG-073891,ASSENATH ACHIENG OTIENO,SIGAMA GAYENA,Bet Kimiyi Farmers Group,Instance 3,Female,50,low,30-65,Female_30-65,HomaBay
...,...,...,...,...,...,...,...,...,...,...,...,...
15755,15756,FG-071316,Millicent Demba Ochieng,Nyaera,Waweya Moyie Farmers Group,Instance 4,Female,47,high,30-65,Female_30-65,Migori
15756,15757,FG-068488,Molly Anyango Otieno,Nyaera,Waweya Moyie Farmers Group,Instance 4,Female,38,high,30-65,Female_30-65,Migori
15757,15758,FG-092514,Peter Ojea Magadi,Nyaera,Waweya Moyie Farmers Group,Instance 4,Male,30,high,30-65,Male_30-65,Migori
15759,15760,FG-068489,Tobias Otieno Olela,Nyaera,Waweya Moyie Farmers Group,Instance 4,Male,38,high,30-65,Male_30-65,Migori
15760,15761,FG-092513,Zablon Mahonga Muyesu,Nyaera,Waweya Moyie Farmers Group,Instance 4,Male,42,high,30-65,Male_30-65,Migori

CREATING THE RANDOM SAMPLE

In [96]:
#Building a strata key
data["strata"]=(
    data["County"].astype(str) + "_"+
    data["age_gender_group"].astype(str) + "_"+
    data["Instance"].astype(str)+ "_" +
    data["village_clusters"].astype(str)
)

In [97]:
print("strata per County:")
print(data.groupby("County")["strata"].nunique())

print("\nCounts per County:")
print(data["County"].value_counts())

strata per County:
County
HomaBay    47
Kisumu     35
Migori     36
Name: strata, dtype: int64

Counts per County:
County
Migori     6202
HomaBay    5017
Kisumu     2520
Name: count, dtype: int64

In [98]:
print(data["County"].unique())      
print(data["strata"].nunique())         
print(data["County"].value_counts())

['HomaBay' 'Migori' 'Kisumu']
118
County
Migori     6202
HomaBay    5017
Kisumu     2520
Name: count, dtype: int64

In [99]:
#Part 5: Proportional Stratified Sampling
samples = []

for County, subset in data.groupby("County"):
    target_n = 40
    
    counts = subset["strata"].value_counts()
    proportions = counts / counts.sum()
    n_per_strata = (proportions * target_n).round().astype(int)

    diff = target_n - n_per_strata.sum()
    if diff != 0:
        n_per_strata.iloc[0] += diff

    strat_samples = []
    for strata, n in n_per_strata.items():
        group = subset[subset["strata"] == strata]
        if len(group) > 0 and n > 0:
            strat_samples.append(group.sample(n=min(n, len(group)), random_state=42))

    if strat_samples:
        samples.append(pd.concat(strat_samples))


if samples:
    random_sample = pd.concat(samples, ignore_index=True)
    print(random_sample.shape)
    print(random_sample["County"].value_counts())

(120, 13)
County
HomaBay    40
Kisumu     40
Migori     40
Name: count, dtype: int64

In [100]:
random_sample

,No,FG ID,Forest Garden Name,Village,Local Group Name,Instance,Gender,Age,village_clusters,age_group,age_gender_group,County,strata
0,4156,FG-076461,ROSE AOKO OGOLA,KABUJA VILLAGE,NYABENDE FARMERS GROUP.,Instance 4,Female,52,high,30-65,Female_30-65,HomaBay,HomaBay_Female_30-65_Instance 4_high
1,5534,FG-075601,Pamela Akeyo Waringa,Magina,Magina Farmers Group,Instance 4,Female,45,high,30-65,Female_30-65,HomaBay,HomaBay_Female_30-65_Instance 4_high
2,6314,FG-082412,TRIZA ADHIAMBO OLOO,Onyege,OPO FARMERS GROUP,Instance 4,Female,43,high,30-65,Female_30-65,HomaBay,HomaBay_Female_30-65_Instance 4_high
3,4182,FG-072494,GRACE ACHIENG ONYANGO,Upper Kodhoch,ODINO FARMERS,Instance 4,Female,47,high,30-65,Female_30-65,HomaBay,HomaBay_Female_30-65_Instance 4_high
4,6234,FG-082171,MARY AKINYI HARAMBEE,ONGAMO,ON'GAMO SMART FARMERS GROUP,Instance 4,Female,48,high,30-65,Female_30-65,HomaBay,HomaBay_Female_30-65_Instance 4_high
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,14973,FG-071866,Caleb Onyango Agunja,Kodhoch village,Kodhoch Tree FARMERS GROUP,Instance 4,Male,36,medium,30-65,Male_30-65,Migori,Migori_Male_30-65_Instance 4_medium
116,15411,FG-092180,Jennifer Odira Owiti,Kwa hill Village,Grace 2 farmers group,Instance 4,Female,52,medium,30-65,Female_30-65,Migori,Migori_Female_30-65_Instance 4_medium
117,12778,FG-090884,ANNE AKINYI JACKTON,Nyamaraga,Kamunga Farmers Group,Instance 4,Female,27,high,17-29,Female_17-29,Migori,Migori_Female_17-29_Instance 4_high
118,11010,FG-069047,Cypranus Omondi Orwa,Mapera Border,Mapera Border Farmers Group,Instance 4,Male,24,low,17-29,Male_17-29,Migori,Migori_Male_17-29_Instance 4_low
119,950,FG-024702,CHARLES ORWA KAWAGA,OKUMBO,OKUMBO A FARMERS GROUP,Instance 2,Male,65,high,30-65,Male_30-65,Migori,Migori_Male_30-65_Instance 2_high

In [126]:
random_sample.drop(columns=["strata"], inplace=True)

In [128]:
random_sample["village_clusters"].value_counts()

village_clusters
high concentration      63
low concentration       31
medium concentration    26
Name: count, dtype: int64

In [130]:
random_sample["village_clusters"] = random_sample["village_clusters"].replace({"high":"high concentration",
                                                                               "medium":"medium concentration",
                                                                               "low": "low concentration"
                                                                              })
random_sample

,No,FG ID,Forest Garden Name,Village,Local Group Name,Instance,Gender,Age,village_clusters,age_group,age_gender_group,County
0,4156,FG-076461,ROSE AOKO OGOLA,KABUJA VILLAGE,NYABENDE FARMERS GROUP.,Instance 4,Female,52,high concentration,30-65,Female_30-65,HomaBay
1,5534,FG-075601,Pamela Akeyo Waringa,Magina,Magina Farmers Group,Instance 4,Female,45,high concentration,30-65,Female_30-65,HomaBay
2,6314,FG-082412,TRIZA ADHIAMBO OLOO,Onyege,OPO FARMERS GROUP,Instance 4,Female,43,high concentration,30-65,Female_30-65,HomaBay
3,4182,FG-072494,GRACE ACHIENG ONYANGO,Upper Kodhoch,ODINO FARMERS,Instance 4,Female,47,high concentration,30-65,Female_30-65,HomaBay
4,6234,FG-082171,MARY AKINYI HARAMBEE,ONGAMO,ON'GAMO SMART FARMERS GROUP,Instance 4,Female,48,high concentration,30-65,Female_30-65,HomaBay
...,...,...,...,...,...,...,...,...,...,...,...,...
115,14973,FG-071866,Caleb Onyango Agunja,Kodhoch village,Kodhoch Tree FARMERS GROUP,Instance 4,Male,36,medium concentration,30-65,Male_30-65,Migori
116,15411,FG-092180,Jennifer Odira Owiti,Kwa hill Village,Grace 2 farmers group,Instance 4,Female,52,medium concentration,30-65,Female_30-65,Migori
117,12778,FG-090884,ANNE AKINYI JACKTON,Nyamaraga,Kamunga Farmers Group,Instance 4,Female,27,high concentration,17-29,Female_17-29,Migori
118,11010,FG-069047,Cypranus Omondi Orwa,Mapera Border,Mapera Border Farmers Group,Instance 4,Male,24,low concentration,17-29,Male_17-29,Migori
119,950,FG-024702,CHARLES ORWA KAWAGA,OKUMBO,OKUMBO A FARMERS GROUP,Instance 2,Male,65,high concentration,30-65,Male_30-65,Migori

In [138]:
random_sample.to_csv("C:\\Users\\Administrator\\OneDrive\\Documents\\Random Sample.csv", index=False)